services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGBASE}
      POSTGRES_PORT: ${PGPORT}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: ${DB_SOURCE_DOCKER}
    depends_on:
      - database
    entrypoint: ["/app/wait-for.sh", "database:${PGPORT}", "--", "/app/start.sh"]
    command: ["/app/main"]
