services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: stopmining
      POSTGRES_USER: admni
      POSTGRES_DB: data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_SOURCE: postgres://admni:stopmining@database:5432/data?sslmode=disable
    depends_on:
      - database
    entrypoint: ["/app/wait-for.sh", "database:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
